# Generated by Django 4.1.5 on 2023-01-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido')),
                ('birthday', models.DateField(auto_now_add=True, verbose_name='Fecha Nacimiento')),
            ],
        ),
    ]
